var searchData=
[
  ['a_20good_20readme_0',['Suggestions for a good README',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['a_20maintainer_20or_20owner_20allowing_20your_20project_20to_20keep_20going_20you_20can_20also_20make_20an_20explicit_20request_20for_20maintainers_1',['If you have run out of energy or time for your project, put a note at the top of the README saying that development has slowed down or stopped completely. Someone may choose to fork your project or volunteer to step in as a maintainer or owner, allowing your project to keep going. You can also make an explicit request for maintainers.',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['a_20note_20at_20the_20top_20of_20the_20readme_20saying_20that_20development_20has_20slowed_20down_20or_20stopped_20completely_20someone_20may_20choose_20to_20fork_20your_20project_20or_20volunteer_20to_20step_20in_20as_20a_20maintainer_20or_20owner_20allowing_20your_20project_20to_20keep_20going_20you_20can_20also_20make_20an_20explicit_20request_20for_20maintainers_2',['If you have run out of energy or time for your project, put a note at the top of the README saying that development has slowed down or stopped completely. Someone may choose to fork your project or volunteer to step in as a maintainer or owner, allowing your project to keep going. You can also make an explicit request for maintainers.',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['acknowledgment_3',['Authors and acknowledgment',['../md__r_e_a_d_m_e.html#autotoc_md17',1,'']]],
  ['add_20your_20files_4',['Add your files',['../md__r_e_a_d_m_e.html#autotoc_md2',1,'']]],
  ['allowing_20your_20project_20to_20keep_20going_20you_20can_20also_20make_20an_20explicit_20request_20for_20maintainers_5',['If you have run out of energy or time for your project, put a note at the top of the README saying that development has slowed down or stopped completely. Someone may choose to fork your project or volunteer to step in as a maintainer or owner, allowing your project to keep going. You can also make an explicit request for maintainers.',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['also_20make_20an_20explicit_20request_20for_20maintainers_6',['If you have run out of energy or time for your project, put a note at the top of the README saying that development has slowed down or stopped completely. Someone may choose to fork your project or volunteer to step in as a maintainer or owner, allowing your project to keep going. You can also make an explicit request for maintainers.',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['an_20explicit_20request_20for_20maintainers_7',['If you have run out of energy or time for your project, put a note at the top of the README saying that development has slowed down or stopped completely. Someone may choose to fork your project or volunteer to step in as a maintainer or owner, allowing your project to keep going. You can also make an explicit request for maintainers.',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['and_20acknowledgment_8',['Authors and acknowledgment',['../md__r_e_a_d_m_e.html#autotoc_md17',1,'']]],
  ['and_20deploy_9',['Test and Deploy',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['as_20a_20maintainer_20or_20owner_20allowing_20your_20project_20to_20keep_20going_20you_20can_20also_20make_20an_20explicit_20request_20for_20maintainers_10',['If you have run out of energy or time for your project, put a note at the top of the README saying that development has slowed down or stopped completely. Someone may choose to fork your project or volunteer to step in as a maintainer or owner, allowing your project to keep going. You can also make an explicit request for maintainers.',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['at_20the_20top_20of_20the_20readme_20saying_20that_20development_20has_20slowed_20down_20or_20stopped_20completely_20someone_20may_20choose_20to_20fork_20your_20project_20or_20volunteer_20to_20step_20in_20as_20a_20maintainer_20or_20owner_20allowing_20your_20project_20to_20keep_20going_20you_20can_20also_20make_20an_20explicit_20request_20for_20maintainers_11',['If you have run out of energy or time for your project, put a note at the top of the README saying that development has slowed down or stopped completely. Someone may choose to fork your project or volunteer to step in as a maintainer or owner, allowing your project to keep going. You can also make an explicit request for maintainers.',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['authors_20and_20acknowledgment_12',['Authors and acknowledgment',['../md__r_e_a_d_m_e.html#autotoc_md17',1,'']]]
];
