var searchData=
[
  ['calc_0',['Polynomial-calc-',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['can_20also_20make_20an_20explicit_20request_20for_20maintainers_1',['If you have run out of energy or time for your project, put a note at the top of the README saying that development has slowed down or stopped completely. Someone may choose to fork your project or volunteer to step in as a maintainer or owner, allowing your project to keep going. You can also make an explicit request for maintainers.',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['choose_20to_20fork_20your_20project_20or_20volunteer_20to_20step_20in_20as_20a_20maintainer_20or_20owner_20allowing_20your_20project_20to_20keep_20going_20you_20can_20also_20make_20an_20explicit_20request_20for_20maintainers_2',['If you have run out of energy or time for your project, put a note at the top of the README saying that development has slowed down or stopped completely. Someone may choose to fork your project or volunteer to step in as a maintainer or owner, allowing your project to keep going. You can also make an explicit request for maintainers.',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['coeffs_3',['coeffs',['../class_polynomial.html#a112c6b7dc3c87acc64c0a62d11ce7a00',1,'Polynomial']]],
  ['collaborate_20with_20your_20team_4',['Collaborate with your team',['../md__r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['completely_20someone_20may_20choose_20to_20fork_20your_20project_20or_20volunteer_20to_20step_20in_20as_20a_20maintainer_20or_20owner_20allowing_20your_20project_20to_20keep_20going_20you_20can_20also_20make_20an_20explicit_20request_20for_20maintainers_5',['If you have run out of energy or time for your project, put a note at the top of the README saying that development has slowed down or stopped completely. Someone may choose to fork your project or volunteer to step in as a maintainer or owner, allowing your project to keep going. You can also make an explicit request for maintainers.',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['contributing_6',['Contributing',['../md__r_e_a_d_m_e.html#autotoc_md16',1,'']]]
];
